name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies (backend)
      run: |
        cd server
        npm install

    - name: Lint backend (if using ESLint)
      run: |
        cd server
        npx eslint . || true

    - name: Install dependencies (frontend)
      run: |
        cd client
        npm install

    - name: Lint frontend (if using ESLint)
      run: |
        cd client
        npx eslint . || true
