name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: habitrack123.azurecr.io
  RESOURCE_GROUP: habitrack-rg
  APP_PLAN: habitrack-plan
  SERVER_APP: habitrack-backend
  CLIENT_APP: habitrack-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies & build client
      working-directory: ./client
      run: |
        npm install
        npm run build

    - name: Build and tag client Docker image
      run: |
        docker build -t $REGISTRY/habitrack-client:v1 ./client

    - name: Build and tag server Docker image
      run: |
        docker build -t $REGISTRY/habitrack-server:v1 ./server

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Push client image to ACR
      run: docker push $REGISTRY/habitrack-client:v1

    - name: Push server image to ACR
      run: docker push $REGISTRY/habitrack-server:v1

    - name: Azure CLI login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy server image to Azure App Service
      run: |
        az webapp config container set \
          --name ${{ env.SERVER_APP }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --container-image-name $REGISTRY/habitrack-server:v1

    - name: Deploy client image to Azure App Service
      run: |
        az webapp config container set \
          --name ${{ env.CLIENT_APP }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --container-image-name $REGISTRY/habitrack-client:v1
